# Generated by Django 3.1.4 on 2020-12-18 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_unicorn'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Unicorn',
        ),
    ]
