# Generated by Django 3.1.2 on 2020-12-14 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201214_0532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='user',
            new_name='owner',
        ),
    ]
